PM.UserAdmin.UI/Controllers/RequestsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.PortableExecutable;
using System.Security.Claims;
using System.Security.Principal;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PM.Auth.GraphApi;
using PM.Business.Dto;
using PM.Business.Email;
using PM.Business.RequestLogging;
using PM.Business.Security;
using PM.Entity.Models;
using PM.Entity.Services;

namespace PM.UserAdmin.UI.Controllers
{
    public class RequestsController : Controller
    {
        private readonly VandivierProductManagerContext _context;
        private readonly IDbReadService _dbReadService;
        private readonly IDbWriteService _dbWriteService;
        private readonly IConfiguration _configuration;
        
		public RequestsController(IDbReadService dbReadService, IDbWriteService dbWriteService, 
			VandivierProductManagerContext context, IConfiguration configuration)
		{
			_dbReadService = dbReadService;
			_dbWriteService = dbWriteService;
	        _context = context;
	        _configuration = configuration;
		}

		[Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		public async Task<IActionResult> Index(string search)
		{
			if (search != null)
			{
				Regex rgx = new Regex("[^a-zA-Z0-9 -]");
				search = rgx.Replace(search, "").ToUpper();
			}

			ViewData["FilterParam"] = search;

			UserDto.UserId = User.Identity.Name;

			_dbReadService.IncludeEntityNavigation<Product>();
	        _dbReadService.IncludeEntityNavigation<Store>();
			_dbReadService.IncludeEntityNavigation<RequestType>();
	        _dbReadService.IncludeEntityNavigation<StatusType>();
	        _dbReadService.IncludeEntityNavigation<Supplier>();

			var requests = await _dbReadService.GetAllRecordsAsync<Request>();
			requests.Reverse();

			var requestsEnumerable = requests.AsEnumerable();

			if (!String.IsNullOrEmpty(search))
			{
				requestsEnumerable = requests.Where(s => s.RequestDescription != null && s.RequestDescription.ToUpper().Contains(search)
				
														|| s.StatusType.StatusTypeName != null && s.StatusType.StatusTypeName.ToUpper().Contains(search)

														|| s.RequestType.RequestTypeName != null && s.RequestType.RequestTypeName.ToUpper().Contains(search)

														|| s.Store.StoreName != null && s.Store.StoreName.ToUpper().Contains(search)

														|| s.ProductId != null && s.Product.ProductName.ToUpper().Contains(search)

														|| s.Id.ToString().StartsWith(search)

														|| s.Id.ToString().Contains(search)

														|| s.CreatedBy != null && s.CreatedBy.ToUpper().Contains(search));
			}

			RequestDto.RequestId = null;
			RequestDto.RequestDescription = null;

			return View(requestsEnumerable.ToList());
		}

		[Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		public async Task<IActionResult> Details(int? id)
        {
	        if (!id.HasValue)
            {
                return NotFound();
            }

			_dbReadService.IncludeEntityNavigation<Product>();
			_dbReadService.IncludeEntityNavigation<Store>();
			_dbReadService.IncludeEntityNavigation<RequestType>();
			_dbReadService.IncludeEntityNavigation<StatusType>();
			_dbReadService.IncludeEntityNavigation<Supplier>();

			var request = await _dbReadService.GetSingleRecordAsync<Request>(s => s.Id.Equals(id));

			if (request == null)
            {
                return NotFound();
            }

			RequestDto.RequestId = request.Id;
			RequestDto.RequestDescription = request.RequestDescription;

			var notes = await _dbReadService.GetAllRecordsAsync<Note>(s => s.RequestId.Equals(id));
			if (notes != null)
			{
				ViewData["NoteId"] = notes;
			}
			
			return View(request);
        }

		[Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		public IActionResult CreateRequest()
		{
			ViewData["RequestTypeId"] = new SelectList(_context.RequestType, "Id", "RequestTypeName");
			ViewData["StatusTypeId"] = new SelectList(_context.StatusType, "Id", "StatusTypeName");
			ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "SupplierName");
			ViewData["StoreId"] = new SelectList(_context.Store, "Id", "StoreSupervisorName");

			return View();
		}

		[Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateRequest([Bind("Id,RequestDescription,RequestTypeId,StatusTypeId,UserId,SupplierId,StoreId,CreatedOn,CreatedBy,UpdatedOn,UpdatedBy")] Request request)
		{
			if (ModelState.IsValid)
			{
				if (User != null)
				{
					string claimTypeEmailAddress = $"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
					var userFullName = User.Claims.FirstOrDefault(x => x.Type == $"name").Value;
					request.UserId = User.Claims.FirstOrDefault(x => x.Type == claimTypeEmailAddress).Value;
					request.CreatedBy = userFullName;
				}

				request.CreatedOn = DateTime.Now;

				var status = await _dbReadService.GetSingleRecordAsync<StatusType>(s => s.StatusTypeName.Equals("New Request"));
				request.StatusTypeId = status.Id;

				_dbWriteService.Add(request);
				await _dbWriteService.SaveChangesAsync();
			}

			RequestDto.RequestId = request.Id;

			return RedirectToAction("CreateProduct", "Products", new { id = request.Id });
		}

		[Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		public async Task<IActionResult> Edit(int? id)
        { 
			if (id == null)
            {
                return NotFound();
            }

            var request = await _dbReadService.GetSingleRecordAsync<Request>(s => s.Id.Equals(id));
            RequestDto.StatusId = request.StatusTypeId;

			if (request == null)
            {
                return NotFound();
            }

			ViewData["ProductId"] = new SelectList(_context.Product, "Id", "ProductName", selectedValue: request.ProductId);
			ViewData["RequestTypeId"] = new SelectList(_context.RequestType, "Id", "RequestTypeName");
			ViewData["StatusTypeId"] = new SelectList(_context.StatusType, "Id", "StatusTypeName");
			ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "SupplierName");
			ViewData["StoreId"] = new SelectList(_context.Store, "Id", "StoreSupervisorName");

			RequestDto.RequestId = request.Id;
			RequestDto.RequestDescription = request.RequestDescription;

			var note = await _dbReadService.GetSingleRecordAsync<Note>(s => s.RequestId.Equals(id));
			if (note != null)
			{
				ViewData["NoteId"] = note.Id;
			}

			return View(request);
        }

		[Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RequestDescription,RequestTypeId,StatusTypeId,UserId,ProductId,SupplierId,StoreId,CreatedOn,CreatedBy,UpdatedOn,UpdatedBy")] Request request)
        {
	        if (id != request.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
	                if (User != null)
	                {
		                string claimTypeEmailAddress = $"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
		                var userFullName = User.Claims.FirstOrDefault(x => x.Type == $"name").Value;
		                request.UserId = User.Claims.FirstOrDefault(x => x.Type == claimTypeEmailAddress).Value;
		                request.UpdatedBy = userFullName;
	                }

					request.UpdatedOn = DateTime.Now;

					request.ProductId = _dbReadService.GetSingleRecordAsync<Request>(p => p.Id.Equals(request.Id)).Result.ProductId;

					_dbWriteService.Update(request);
					await _dbWriteService.SaveChangesAsync();

					var status = await _dbReadService.GetSingleRecordAsync<StatusType>(s => s.Id.Equals(request.StatusTypeId));
					if (request.StatusTypeId != RequestDto.StatusId)
					{
						switch (status.StatusTypeName)
						{
							case "New Request":
								break;
							case "Approved":
								RequestLogHelper logHelperApproved = new RequestLogHelper();
								logHelperApproved.LogRequestChange(request, _context, RequestLogConstants.RequestApproved);

								RequestEmail requestEmailManager = new RequestEmail(_configuration, _dbReadService);
								requestEmailManager.SendApprovedRequestEmailToHeadQuarters(request);
								break;

							case "Denied":
								RequestLogHelper logHelperDenied = new RequestLogHelper();
								logHelperDenied.LogRequestChange(request, _context, RequestLogConstants.RequestDenied);

								RequestEmail requestEmailOriginator = new RequestEmail(_configuration, _dbReadService);
								requestEmailOriginator.SendDeniedRequestEmailToOriginatingUser(request);

								break;

							case "Complete":
								RequestLogHelper logHelperComplete = new RequestLogHelper();
								logHelperComplete.LogRequestChange(request, _context, RequestLogConstants.RequestComplete);

								RequestEmail requestEmailCompletedStatus = new RequestEmail(_configuration, _dbReadService);
								requestEmailCompletedStatus.SendRequestCompletedToGroup(request);
								break;
						}
					}
                }
				catch (DbUpdateConcurrencyException)
                {
	                bool result = await RequestExists(request.Id);
	                if (!result)
					{
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            RequestDto.StatusId = null;
            return View(request);
        }

        [Authorize(Policy = GroupAuthorization.EmployeePolicyName)]
		public async Task<IActionResult> Delete(int? id)
        {

PM.UserAdmin.UI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PM.Auth.GraphApi;
using PM.Entity.Services;
using PM.Entity.Models;

namespace PM.UserAdmin.UI.Controllers
{
    public class UsersController : Controller
    {
        private VandivierProductManagerContext _context;
        private readonly Microsoft.Extensions.Configuration.IConfiguration Configuration;
        private readonly IDbReadService _dbReadService;
        private readonly IDbWriteService _dbWriteService;

        public UsersController(VandivierProductManagerContext context, IConfiguration configuration,
            IDbReadService dbReadService, IDbWriteService dbWriteService)

        {
            _context = context;
            Configuration = configuration;
            _dbReadService = dbReadService;
            _dbWriteService = dbWriteService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            _dbReadService.IncludeEntityNavigation<Supplier>();
            var users = await _dbReadService.GetAllRecordsAsync<User>();

            return View(users.OrderBy(s => s.LastName));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _dbReadService.IncludeEntityNavigation<Supplier>();
            var user = await _dbReadService.GetSingleRecordAsync<User>(u => u.Id.Equals(id));

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        public IActionResult Create()
        {
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "SupplierName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SupplierId,FirstName,LastName,EmailAddress,AuthId,CreatedOn,CreatedBy,UpdatedOn,UpdatedBy")] User user)
        {
	        var userFullName = User.Claims.FirstOrDefault(x => x.Type == $"name").Value;

			if (ModelState.IsValid)
            {
	            if (User != null)
	            {
		            user.CreatedBy = userFullName;
	            }

	            user.CreatedOn = DateTime.Now;

				var graphClient = new GraphClient(Configuration, true);
                var password = string.Empty;
                var graphResult = graphClient.CreateUser(user, out password);

                if (graphResult)
                {
                    _dbWriteService.Add(user);

                    var saveResult = await _dbWriteService.SaveChangesAsync();

                    if (saveResult)
                    {
                        var userEmail = new PM.Business.Email.User(Configuration);

                        userEmail.SendWelcomeEmail(user, password);

                        return RedirectToAction(nameof(Index));
                    }

                    // Failed to save to the database, delete the user from the directory.
                    graphClient.DeleteUser(user.AuthId);
                }
            }

            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "SupplierName", user.SupplierId);

            return View(user);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _dbReadService.GetSingleRecordAsync<User>(s => s.Id.Equals(id));
            if (user == null)
            {
                return NotFound();
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "SupplierName", user.SupplierId);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SupplierId,FirstName,LastName,EmailAddress,AuthId,CreatedOn,CreatedBy,UpdatedOn,UpdatedBy")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
	                if (User != null)
	                {
		                var userFullName = User.Claims.FirstOrDefault(x => x.Type == $"name").Value;
		                user.UpdatedBy = userFullName;
	                }

	                user.UpdatedOn = DateTime.Now;

					_dbWriteService.Update(user);

                    await _dbWriteService.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "SupplierName", user.SupplierId);
            return View(user);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _dbReadService.IncludeEntityNavigation<Supplier>();
            var user = await _dbReadService.GetSingleRecordAsync<User>(u => u.Id.Equals(id));

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _dbReadService.GetSingleRecordAsync<User>(u => u.Id.Equals(id));

            var graphClient = new GraphClient(Configuration, true);
            var graphResult = graphClient.DeleteUser(user.AuthId);

            if (graphResult)
            {
                _dbWriteService.Delete(user);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

PM.UserAdmin.UI/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    @ViewBag.Error
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Requests" asp-action="Index"><img src=@Url.Content("~/images/vanlogo.jpg") alt="Product Manager" /></a>
	            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
	                    aria-expanded="false" aria-label="Toggle navigation">
		            <span class="navbar-toggler-icon"></span>
	            </button>
	            @if (@PM.Business.Dto.RequestDto.RequestId != null)
	            {
		            <a asp-controller="Requests" asp-action="Details" asp-route-id=@PM.Business.Dto.RequestDto.RequestId
		               class="nav-link" style="font-size: 16pt; color:#6A0D1F">Request: @PM.Business.Dto.RequestDto.RequestDescription</a>
	            }
	            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse dropdown">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index" style="position: relative">Supplier</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index" style="position: relative">User</a>
                                </li>
                            </ul>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@(((ClaimsIdentity)User.Identity).Claims.Single(x => x.Type == "name").Value)</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut" style="position: relative">Sign Out</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
	        <p style="color: red">@Html.Raw(TempData["notifyUser"])</p>
	        <p style="color: green">@Html.Raw(TempData["notifyUserSuccess"])</p>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Vandivier PM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>